// ─────────────────────────────────────────────────────────────
//  src/admin/employeemanagement/sharedData.js
//
//  Single source of truth for Employee Management module.
//  Import from EditEmployee.jsx, ProfileChangeRequests.jsx, etc.
// ─────────────────────────────────────────────────────────────

/* ─── Design tokens (identical to AdminDashboard / EmployeeList) ─── */
export const C = {
  bg: "#F0F2F8",
  bgMid: "#E8EBF4",
  surface: "#FFFFFF",
  surfaceHover: "#F7F8FC",
  surfaceAlt: "#F7F8FC",
  border: "#E4E7F0",
  borderHover: "rgba(79,70,229,0.35)",
  primary: "#4F46E5",
  primaryLight: "#EEF2FF",
  primaryGlow: "rgba(79,70,229,0.20)",
  accent: "#06B6D4",
  accentLight: "#ECFEFF",
  success: "#10B981",
  successLight: "#D1FAE5",
  warning: "#F59E0B",
  warningLight: "#FEF3C7",
  danger: "#EF4444",
  dangerLight: "#FEE2E2",
  purple: "#8B5CF6",
  purpleLight: "#EDE9FE",
  pink: "#EC4899",
  pinkLight: "#FDF2F8",
  textPrimary: "#0F172A",
  textSecondary: "#64748B",
  textMuted: "#94A3B8",
  navy: "#1E1B4B",
};

export const GRADE_LEVELS = [
  {
    id: "g1",
    name: "Entry Level",
    bg: "#EEF2FF",
    color: "#4F46E5",
    minSalary: 100000,
    maxSalary: 250000,
  },
  {
    id: "g2",
    name: "Intermediate",
    bg: "#F0FDF4",
    color: "#16A34A",
    minSalary: 250000,
    maxSalary: 500000,
  },
  {
    id: "g3",
    name: "Senior",
    bg: "#FFFBEB",
    color: "#D97706",
    minSalary: 500000,
    maxSalary: 1000000,
  },
  {
    id: "g4",
    name: "Management",
    bg: "#FAF5FF",
    color: "#9333EA",
    minSalary: 1000000,
    maxSalary: 2500000,
  },
  {
    id: "g5",
    name: "Executive",
    bg: "#FEF2F2",
    color: "#DC2626",
    minSalary: 2500000,
    maxSalary: 5000000,
  },
];

export const ADMIN = {
  name: "Ngozi Adeleke",
  initials: "NA",
  role: "HR Administrator",
  id: "ADM-001",
};

export const DEPT_COLORS = {
  Engineering: "#6366F1",
  "Product & Design": "#06B6D4",
  Finance: "#10B981",
  "Human Resources": "#F59E0B",
  Operations: "#EC4899",
  Marketing: "#8B5CF6",
  Legal: "#EF4444",
  Sales: "#F97316",
};

export const DEPARTMENTS = Object.keys(DEPT_COLORS);

export const ROLES_BY_DEPT = {
  Engineering: [
    "Backend Engineer",
    "Frontend Engineer",
    "DevOps Engineer",
    "Cloud Architect",
    "QA Engineer",
    "ML Engineer",
    "Mobile Engineer",
    "Platform Engineer",
    "Security Engineer",
    "Senior Backend Engineer",
    "Data Engineer",
  ],
  "Product & Design": [
    "Senior Product Designer",
    "UI/UX Designer",
    "Head of Product",
    "Product Manager",
    "Design Researcher",
    "Design Lead",
  ],
  Finance: [
    "Financial Analyst",
    "Finance Manager",
    "Accountant",
    "Senior Accountant",
    "Financial Controller",
    "Treasury Analyst",
  ],
  "Human Resources": [
    "HR Generalist",
    "HR Administrator",
    "Recruitment Lead",
    "HRBP",
    "Learning & Dev Specialist",
  ],
  Operations: [
    "Operations Manager",
    "Logistics Coordinator",
    "Supply Chain Analyst",
  ],
  Marketing: [
    "Marketing Manager",
    "Content Strategist",
    "Brand Designer",
    "Digital Marketer",
  ],
  Legal: ["Legal Counsel", "Compliance Officer"],
  Sales: ["Sales Director", "Account Executive", "Sales Representative"],
};

export const LOCATIONS = ["Lagos HQ", "Abuja", "Remote"];
export const EMP_TYPES = ["Full-Time", "Part-Time", "Contract"];
export const STATUSES = ["Active", "On Leave", "Inactive"];
export const GRADES = ["L1", "L2", "L3", "L4", "L5", "L6", "L7"];

/* ─── 40 Employees ─── */
export const INITIAL_EMPLOYEES = [
  // ── Product & Design ──────────────────────────────────────
  {
    id: "EMP-001",
    name: "Amara Johnson",
    initials: "AJ",
    dept: "Product & Design",
    role: "Senior Product Designer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2021-06-01",
    grade: "L5",
    email: "amara.johnson@hriscloud.com",
    phone: "+234 801 234 5678",
    gender: "Female",
    dob: "1990-03-15",
    manager: "Chioma Okafor",
    managerDept: "Product & Design",
    bankName: "Zenith Bank",
    accountNo: "2134567890",
  },
  {
    id: "EMP-002",
    name: "Tunde Adeyemi",
    initials: "TA",
    dept: "Product & Design",
    role: "UI/UX Designer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2023-01-15",
    grade: "L3",
    email: "tunde.adeyemi@hriscloud.com",
    phone: "+234 803 456 7890",
    gender: "Male",
    dob: "1995-07-22",
    manager: "Amara Johnson",
    managerDept: "Product & Design",
    bankName: "GTBank",
    accountNo: "0198765432",
  },
  {
    id: "EMP-003",
    name: "Chioma Okafor",
    initials: "CO",
    dept: "Product & Design",
    role: "Head of Product",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2019-03-10",
    grade: "L7",
    email: "chioma.okafor@hriscloud.com",
    phone: "+234 805 678 9012",
    gender: "Female",
    dob: "1985-11-04",
    manager: "",
    managerDept: "",
    bankName: "First Bank",
    accountNo: "3012345678",
  },
  {
    id: "EMP-004",
    name: "Bola Fashola",
    initials: "BF",
    dept: "Product & Design",
    role: "Product Manager",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-08-01",
    grade: "L4",
    email: "bola.fashola@hriscloud.com",
    phone: "+234 807 890 1234",
    gender: "Male",
    dob: "1992-05-30",
    manager: "Chioma Okafor",
    managerDept: "Product & Design",
    bankName: "Access Bank",
    accountNo: "1123456789",
  },
  {
    id: "EMP-005",
    name: "Ngozi Eze",
    initials: "NE",
    dept: "Product & Design",
    role: "Design Researcher",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "On Leave",
    joined: "2023-06-01",
    grade: "L3",
    email: "ngozi.eze@hriscloud.com",
    phone: "+234 809 012 3456",
    gender: "Female",
    dob: "1997-02-11",
    manager: "Amara Johnson",
    managerDept: "Product & Design",
    bankName: "UBA",
    accountNo: "2012345678",
  },
  {
    id: "EMP-032",
    name: "Isioma Chukwu",
    initials: "IC",
    dept: "Product & Design",
    role: "Design Lead",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2021-03-01",
    grade: "L5",
    email: "isioma.chukwu@hriscloud.com",
    phone: "+234 812 345 6789",
    gender: "Female",
    dob: "1991-08-20",
    manager: "Chioma Okafor",
    managerDept: "Product & Design",
    bankName: "Zenith Bank",
    accountNo: "3456789012",
  },

  // ── Engineering ───────────────────────────────────────────
  {
    id: "EMP-006",
    name: "Tunde Bakare",
    initials: "TB",
    dept: "Engineering",
    role: "Backend Engineer",
    location: "Abuja",
    type: "Full-Time",
    status: "Active",
    joined: "2026-03-20",
    grade: "L3",
    email: "tunde.bakare@hriscloud.com",
    phone: "+234 811 234 5678",
    gender: "Male",
    dob: "1998-09-15",
    manager: "Chidi Nwachukwu",
    managerDept: "Engineering",
    bankName: "Zenith Bank",
    accountNo: "4567890123",
  },
  {
    id: "EMP-007",
    name: "Sade Okonkwo",
    initials: "SO",
    dept: "Engineering",
    role: "Frontend Engineer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2026-03-18",
    grade: "L3",
    email: "sade.okonkwo@hriscloud.com",
    phone: "+234 813 456 7890",
    gender: "Female",
    dob: "1999-01-10",
    manager: "Chidi Nwachukwu",
    managerDept: "Engineering",
    bankName: "GTBank",
    accountNo: "5678901234",
  },
  {
    id: "EMP-009",
    name: "Fatima Bello",
    initials: "FB",
    dept: "Engineering",
    role: "DevOps Engineer",
    location: "Remote",
    type: "Full-Time",
    status: "Active",
    joined: "2026-03-12",
    grade: "L4",
    email: "fatima.bello@hriscloud.com",
    phone: "+234 815 678 9012",
    gender: "Female",
    dob: "1993-04-25",
    manager: "Akin Adebayo",
    managerDept: "Engineering",
    bankName: "First Bank",
    accountNo: "6789012345",
  },
  {
    id: "EMP-010",
    name: "Chidi Nwachukwu",
    initials: "CN",
    dept: "Engineering",
    role: "Senior Backend Engineer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-02-02",
    grade: "L5",
    email: "chidi.nwachukwu@hriscloud.com",
    phone: "+234 816 789 0123",
    gender: "Male",
    dob: "1990-12-08",
    manager: "Akin Adebayo",
    managerDept: "Engineering",
    bankName: "Access Bank",
    accountNo: "7890123456",
  },
  {
    id: "EMP-015",
    name: "Akin Adebayo",
    initials: "AA",
    dept: "Engineering",
    role: "Cloud Architect",
    location: "Remote",
    type: "Full-Time",
    status: "Active",
    joined: "2021-09-12",
    grade: "L6",
    email: "akin.adebayo@hriscloud.com",
    phone: "+234 817 890 1234",
    gender: "Male",
    dob: "1987-06-14",
    manager: "",
    managerDept: "",
    bankName: "UBA",
    accountNo: "8901234567",
  },
  {
    id: "EMP-019",
    name: "Amaka Nwosu",
    initials: "AN",
    dept: "Engineering",
    role: "QA Engineer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-11-03",
    grade: "L3",
    email: "amaka.nwosu@hriscloud.com",
    phone: "+234 818 901 2345",
    gender: "Female",
    dob: "1996-03-28",
    manager: "Chidi Nwachukwu",
    managerDept: "Engineering",
    bankName: "Zenith Bank",
    accountNo: "9012345678",
  },
  {
    id: "EMP-024",
    name: "Precious Onyeka",
    initials: "PO",
    dept: "Engineering",
    role: "Mobile Engineer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2023-10-01",
    grade: "L3",
    email: "precious.onyeka@hriscloud.com",
    phone: "+234 819 012 3456",
    gender: "Female",
    dob: "1998-11-30",
    manager: "Chidi Nwachukwu",
    managerDept: "Engineering",
    bankName: "GTBank",
    accountNo: "0123456789",
  },
  {
    id: "EMP-029",
    name: "Uche Okonkwo",
    initials: "UO",
    dept: "Engineering",
    role: "Data Engineer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-05-12",
    grade: "L4",
    email: "uche.okonkwo@hriscloud.com",
    phone: "+234 820 123 4567",
    gender: "Male",
    dob: "1993-07-17",
    manager: "Akin Adebayo",
    managerDept: "Engineering",
    bankName: "Access Bank",
    accountNo: "1234567891",
  },
  {
    id: "EMP-031",
    name: "Taiwo Olatunde",
    initials: "TO",
    dept: "Engineering",
    role: "Security Engineer",
    location: "Remote",
    type: "Full-Time",
    status: "Active",
    joined: "2022-07-01",
    grade: "L4",
    email: "taiwo.olatunde@hriscloud.com",
    phone: "+234 821 234 5678",
    gender: "Male",
    dob: "1992-02-03",
    manager: "Akin Adebayo",
    managerDept: "Engineering",
    bankName: "First Bank",
    accountNo: "2345678902",
  },
  {
    id: "EMP-035",
    name: "Olumide Badmus",
    initials: "OB",
    dept: "Engineering",
    role: "ML Engineer",
    location: "Remote",
    type: "Full-Time",
    status: "Active",
    joined: "2022-12-01",
    grade: "L4",
    email: "olumide.badmus@hriscloud.com",
    phone: "+234 822 345 6789",
    gender: "Male",
    dob: "1991-10-22",
    manager: "Akin Adebayo",
    managerDept: "Engineering",
    bankName: "UBA",
    accountNo: "3456789013",
  },
  {
    id: "EMP-040",
    name: "Chinedu Ugwu",
    initials: "CU",
    dept: "Engineering",
    role: "Platform Engineer",
    location: "Abuja",
    type: "Full-Time",
    status: "Inactive",
    joined: "2021-10-01",
    grade: "L3",
    email: "chinedu.ugwu@hriscloud.com",
    phone: "+234 823 456 7890",
    gender: "Male",
    dob: "1994-05-09",
    manager: "Chidi Nwachukwu",
    managerDept: "Engineering",
    bankName: "GTBank",
    accountNo: "4567890124",
  },

  // ── Finance ───────────────────────────────────────────────
  {
    id: "EMP-008",
    name: "Emeka Eze",
    initials: "EE",
    dept: "Finance",
    role: "Financial Analyst",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2026-03-15",
    grade: "L3",
    email: "emeka.eze@hriscloud.com",
    phone: "+234 824 567 8901",
    gender: "Male",
    dob: "1997-08-12",
    manager: "Adaeze Obi",
    managerDept: "Finance",
    bankName: "Zenith Bank",
    accountNo: "5678901235",
  },
  {
    id: "EMP-011",
    name: "Adaeze Obi",
    initials: "AO",
    dept: "Finance",
    role: "Finance Manager",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2020-05-05",
    grade: "L5",
    email: "adaeze.obi@hriscloud.com",
    phone: "+234 825 678 9012",
    gender: "Female",
    dob: "1988-04-17",
    manager: "",
    managerDept: "",
    bankName: "Access Bank",
    accountNo: "6789012346",
  },
  {
    id: "EMP-014",
    name: "Chidinma Okafor",
    initials: "CO",
    dept: "Finance",
    role: "Accountant",
    location: "Lagos HQ",
    type: "Contract",
    status: "Active",
    joined: "2023-07-01",
    grade: "L3",
    email: "chidinma.okafor@hriscloud.com",
    phone: "+234 826 789 0123",
    gender: "Female",
    dob: "1996-06-05",
    manager: "Adaeze Obi",
    managerDept: "Finance",
    bankName: "First Bank",
    accountNo: "7890123457",
  },
  {
    id: "EMP-018",
    name: "Chukwuemeka Obi",
    initials: "CO",
    dept: "Finance",
    role: "Senior Accountant",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2019-04-14",
    grade: "L4",
    email: "chukwuemeka.obi@hriscloud.com",
    phone: "+234 827 890 1234",
    gender: "Male",
    dob: "1989-01-30",
    manager: "Adaeze Obi",
    managerDept: "Finance",
    bankName: "UBA",
    accountNo: "8901234568",
  },
  {
    id: "EMP-026",
    name: "Temitope Salami",
    initials: "TS",
    dept: "Finance",
    role: "Treasury Analyst",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-06-01",
    grade: "L3",
    email: "temitope.salami@hriscloud.com",
    phone: "+234 828 901 2345",
    gender: "Male",
    dob: "1994-12-18",
    manager: "Adaeze Obi",
    managerDept: "Finance",
    bankName: "GTBank",
    accountNo: "9012345679",
  },
  {
    id: "EMP-036",
    name: "Halima Sule",
    initials: "HS",
    dept: "Finance",
    role: "Financial Controller",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "On Leave",
    joined: "2020-08-01",
    grade: "L5",
    email: "halima.sule@hriscloud.com",
    phone: "+234 829 012 3456",
    gender: "Female",
    dob: "1988-07-14",
    manager: "",
    managerDept: "",
    bankName: "Access Bank",
    accountNo: "0123456780",
  },

  // ── Human Resources ───────────────────────────────────────
  {
    id: "EMP-012",
    name: "Kola Adeyemi",
    initials: "KA",
    dept: "Human Resources",
    role: "HR Generalist",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2021-10-10",
    grade: "L3",
    email: "kola.adeyemi@hriscloud.com",
    phone: "+234 830 123 4567",
    gender: "Male",
    dob: "1994-09-03",
    manager: "Ngozi Adeleke",
    managerDept: "Human Resources",
    bankName: "Zenith Bank",
    accountNo: "1234567892",
  },
  {
    id: "EMP-016",
    name: "Ngozi Adeleke",
    initials: "NA",
    dept: "Human Resources",
    role: "HR Administrator",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2018-03-01",
    grade: "L7",
    email: "ngozi.adeleke@hriscloud.com",
    phone: "+234 831 234 5678",
    gender: "Female",
    dob: "1983-11-25",
    manager: "",
    managerDept: "",
    bankName: "First Bank",
    accountNo: "2345678903",
  },
  {
    id: "EMP-017",
    name: "Seun Afolabi",
    initials: "SA",
    dept: "Human Resources",
    role: "Recruitment Lead",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2021-03-28",
    grade: "L4",
    email: "seun.afolabi@hriscloud.com",
    phone: "+234 832 345 6789",
    gender: "Male",
    dob: "1991-03-28",
    manager: "Ngozi Adeleke",
    managerDept: "Human Resources",
    bankName: "UBA",
    accountNo: "3456789014",
  },
  {
    id: "EMP-030",
    name: "Funmilayo Bello",
    initials: "FB",
    dept: "Human Resources",
    role: "Learning & Dev Specialist",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2023-01-20",
    grade: "L3",
    email: "funmilayo.bello@hriscloud.com",
    phone: "+234 833 456 7890",
    gender: "Female",
    dob: "1996-04-15",
    manager: "Ngozi Adeleke",
    managerDept: "Human Resources",
    bankName: "GTBank",
    accountNo: "4567890125",
  },
  {
    id: "EMP-039",
    name: "Toyin Adeola",
    initials: "TA",
    dept: "Human Resources",
    role: "HRBP",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-02-01",
    grade: "L4",
    email: "toyin.adeola@hriscloud.com",
    phone: "+234 834 567 8901",
    gender: "Female",
    dob: "1992-08-07",
    manager: "Ngozi Adeleke",
    managerDept: "Human Resources",
    bankName: "Access Bank",
    accountNo: "5678901236",
  },

  // ── Operations ────────────────────────────────────────────
  {
    id: "EMP-013",
    name: "Ibrahim Musa",
    initials: "IM",
    dept: "Operations",
    role: "Operations Manager",
    location: "Abuja",
    type: "Full-Time",
    status: "Active",
    joined: "2020-01-08",
    grade: "L5",
    email: "ibrahim.musa@hriscloud.com",
    phone: "+234 835 678 9012",
    gender: "Male",
    dob: "1987-02-19",
    manager: "",
    managerDept: "",
    bankName: "First Bank",
    accountNo: "6789012347",
  },
  {
    id: "EMP-025",
    name: "Adebisi Ogunleye",
    initials: "AO",
    dept: "Operations",
    role: "Supply Chain Analyst",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Inactive",
    joined: "2020-03-01",
    grade: "L3",
    email: "adebisi.ogunleye@hriscloud.com",
    phone: "+234 836 789 0123",
    gender: "Female",
    dob: "1993-10-11",
    manager: "Ibrahim Musa",
    managerDept: "Operations",
    bankName: "UBA",
    accountNo: "7890123458",
  },
  {
    id: "EMP-033",
    name: "Musa Aliyu",
    initials: "MA",
    dept: "Operations",
    role: "Logistics Coordinator",
    location: "Abuja",
    type: "Full-Time",
    status: "Active",
    joined: "2021-11-01",
    grade: "L3",
    email: "musa.aliyu@hriscloud.com",
    phone: "+234 837 890 1234",
    gender: "Male",
    dob: "1995-06-22",
    manager: "Ibrahim Musa",
    managerDept: "Operations",
    bankName: "GTBank",
    accountNo: "8901234569",
  },

  // ── Marketing ─────────────────────────────────────────────
  {
    id: "EMP-020",
    name: "Yemi Olatunji",
    initials: "YO",
    dept: "Marketing",
    role: "Marketing Manager",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2020-06-05",
    grade: "L5",
    email: "yemi.olatunji@hriscloud.com",
    phone: "+234 838 901 2345",
    gender: "Male",
    dob: "1988-08-31",
    manager: "",
    managerDept: "",
    bankName: "Access Bank",
    accountNo: "9012345670",
  },
  {
    id: "EMP-021",
    name: "Damilola Coker",
    initials: "DC",
    dept: "Marketing",
    role: "Content Strategist",
    location: "Remote",
    type: "Part-Time",
    status: "Active",
    joined: "2023-02-15",
    grade: "L3",
    email: "damilola.coker@hriscloud.com",
    phone: "+234 839 012 3456",
    gender: "Female",
    dob: "1996-01-14",
    manager: "Yemi Olatunji",
    managerDept: "Marketing",
    bankName: "First Bank",
    accountNo: "0123456781",
  },
  {
    id: "EMP-027",
    name: "Bunmi Oye",
    initials: "BO",
    dept: "Marketing",
    role: "Brand Designer",
    location: "Remote",
    type: "Contract",
    status: "Active",
    joined: "2023-09-01",
    grade: "L3",
    email: "bunmi.oye@hriscloud.com",
    phone: "+234 840 123 4567",
    gender: "Female",
    dob: "1997-03-09",
    manager: "Yemi Olatunji",
    managerDept: "Marketing",
    bankName: "UBA",
    accountNo: "1234567893",
  },
  {
    id: "EMP-038",
    name: "Nneka Obi",
    initials: "NO",
    dept: "Marketing",
    role: "Digital Marketer",
    location: "Lagos HQ",
    type: "Part-Time",
    status: "Active",
    joined: "2023-06-01",
    grade: "L3",
    email: "nneka.obi@hriscloud.com",
    phone: "+234 841 234 5678",
    gender: "Female",
    dob: "1998-07-02",
    manager: "Yemi Olatunji",
    managerDept: "Marketing",
    bankName: "GTBank",
    accountNo: "2345678904",
  },

  // ── Legal ─────────────────────────────────────────────────
  {
    id: "EMP-022",
    name: "Rukayat Lawal",
    initials: "RL",
    dept: "Legal",
    role: "Legal Counsel",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2021-08-22",
    grade: "L5",
    email: "rukayat.lawal@hriscloud.com",
    phone: "+234 842 345 6789",
    gender: "Female",
    dob: "1989-12-01",
    manager: "",
    managerDept: "",
    bankName: "Access Bank",
    accountNo: "3456789015",
  },
  {
    id: "EMP-034",
    name: "Grace Ekwueme",
    initials: "GE",
    dept: "Legal",
    role: "Compliance Officer",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2022-04-01",
    grade: "L4",
    email: "grace.ekwueme@hriscloud.com",
    phone: "+234 843 456 7890",
    gender: "Female",
    dob: "1992-09-16",
    manager: "Rukayat Lawal",
    managerDept: "Legal",
    bankName: "First Bank",
    accountNo: "4567890126",
  },

  // ── Sales ─────────────────────────────────────────────────
  {
    id: "EMP-023",
    name: "Gbenga Oduola",
    initials: "GO",
    dept: "Sales",
    role: "Sales Director",
    location: "Abuja",
    type: "Full-Time",
    status: "Active",
    joined: "2020-01-12",
    grade: "L6",
    email: "gbenga.oduola@hriscloud.com",
    phone: "+234 844 567 8901",
    gender: "Male",
    dob: "1985-05-28",
    manager: "",
    managerDept: "",
    bankName: "UBA",
    accountNo: "5678901237",
  },
  {
    id: "EMP-028",
    name: "Tola Akinfenwa",
    initials: "TA",
    dept: "Sales",
    role: "Account Executive",
    location: "Abuja",
    type: "Full-Time",
    status: "Active",
    joined: "2023-02-01",
    grade: "L3",
    email: "tola.akinfenwa@hriscloud.com",
    phone: "+234 845 678 9012",
    gender: "Male",
    dob: "1995-11-11",
    manager: "Gbenga Oduola",
    managerDept: "Sales",
    bankName: "GTBank",
    accountNo: "6789012348",
  },
  {
    id: "EMP-037",
    name: "Rotimi Fashola",
    initials: "RF",
    dept: "Sales",
    role: "Sales Representative",
    location: "Lagos HQ",
    type: "Full-Time",
    status: "Active",
    joined: "2024-03-01",
    grade: "L2",
    email: "rotimi.fashola@hriscloud.com",
    phone: "+234 846 789 0123",
    gender: "Male",
    dob: "1999-02-22",
    manager: "Gbenga Oduola",
    managerDept: "Sales",
    bankName: "Access Bank",
    accountNo: "7890123459",
  },
];

/* ─── Mock profile change requests ─── */
export const INITIAL_REQUESTS = [
  {
    id: "REQ-001",
    employeeId: "EMP-001",
    employeeName: "Amara Johnson",
    employeeInitials: "AJ",
    dept: "Product & Design",
    field: "Phone Number",
    fieldKey: "phone",
    oldValue: "+234 801 111 1111",
    newValue: "+234 801 234 5678",
    reason: "SIM card replaced",
    status: "pending",
    submittedDate: "2026-06-28",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
  {
    id: "REQ-002",
    employeeId: "EMP-002",
    employeeName: "Tunde Adeyemi",
    employeeInitials: "TA",
    dept: "Product & Design",
    field: "Residential Address",
    fieldKey: "address",
    oldValue: "3 Allen Ave, Ikeja",
    newValue: "15 Lekki Phase 1, Lagos",
    reason: "Relocated after marriage",
    status: "pending",
    submittedDate: "2026-06-27",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
  {
    id: "REQ-003",
    employeeId: "EMP-008",
    employeeName: "Emeka Eze",
    employeeInitials: "EE",
    dept: "Finance",
    field: "Bank Account Number",
    fieldKey: "accountNo",
    oldValue: "5678901234",
    newValue: "5678901235",
    reason: "Old account closed by bank",
    status: "pending",
    submittedDate: "2026-06-26",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
  {
    id: "REQ-004",
    employeeId: "EMP-010",
    employeeName: "Chidi Nwachukwu",
    employeeInitials: "CN",
    dept: "Engineering",
    field: "Email Address",
    fieldKey: "email",
    oldValue: "chidi.old@hriscloud.com",
    newValue: "chidi.nwachukwu@hriscloud.com",
    reason: "Previous email decommissioned",
    status: "approved",
    submittedDate: "2026-06-20",
    reviewedBy: "Ngozi Adeleke",
    reviewedDate: "2026-06-22",
    rejectReason: null,
  },
  {
    id: "REQ-005",
    employeeId: "EMP-005",
    employeeName: "Ngozi Eze",
    employeeInitials: "NE",
    dept: "Product & Design",
    field: "Next of Kin Name",
    fieldKey: "nextOfKin",
    oldValue: "Chidi Eze",
    newValue: "Amaka Eze",
    reason: "Name spelling correction",
    status: "rejected",
    submittedDate: "2026-06-18",
    reviewedBy: "Ngozi Adeleke",
    reviewedDate: "2026-06-19",
    rejectReason: "Supporting document required",
  },
  {
    id: "REQ-006",
    employeeId: "EMP-012",
    employeeName: "Kola Adeyemi",
    employeeInitials: "KA",
    dept: "Human Resources",
    field: "Date of Birth",
    fieldKey: "dob",
    oldValue: "1994-09-13",
    newValue: "1994-09-03",
    reason: "Typographical error on original form",
    status: "pending",
    submittedDate: "2026-06-25",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
  {
    id: "REQ-007",
    employeeId: "EMP-020",
    employeeName: "Yemi Olatunji",
    employeeInitials: "YO",
    dept: "Marketing",
    field: "Phone Number",
    fieldKey: "phone",
    oldValue: "+234 838 000 0000",
    newValue: "+234 838 901 2345",
    reason: "Updated to new corporate line",
    status: "approved",
    submittedDate: "2026-06-15",
    reviewedBy: "Ngozi Adeleke",
    reviewedDate: "2026-06-17",
    rejectReason: null,
  },
  {
    id: "REQ-008",
    employeeId: "EMP-022",
    employeeName: "Rukayat Lawal",
    employeeInitials: "RL",
    dept: "Legal",
    field: "Bank Name",
    fieldKey: "bankName",
    oldValue: "Sterling Bank",
    newValue: "Access Bank",
    reason: "Switched primary bank account",
    status: "pending",
    submittedDate: "2026-06-29",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
  {
    id: "REQ-009",
    employeeId: "EMP-036",
    employeeName: "Halima Sule",
    employeeInitials: "HS",
    dept: "Finance",
    field: "Email Address",
    fieldKey: "email",
    oldValue: "h.sule@hriscloud.com",
    newValue: "halima.sule@hriscloud.com",
    reason: "Standardise email format",
    status: "rejected",
    submittedDate: "2026-06-10",
    reviewedBy: "Ngozi Adeleke",
    reviewedDate: "2026-06-12",
    rejectReason: "IT must raise this request",
  },
  {
    id: "REQ-010",
    employeeId: "EMP-017",
    employeeName: "Seun Afolabi",
    employeeInitials: "SA",
    dept: "Human Resources",
    field: "Phone Number",
    fieldKey: "phone",
    oldValue: "+234 832 000 0000",
    newValue: "+234 832 345 6789",
    reason: "New number after porting",
    status: "approved",
    submittedDate: "2026-06-08",
    reviewedBy: "Ngozi Adeleke",
    reviewedDate: "2026-06-09",
    rejectReason: null,
  },
  {
    id: "REQ-011",
    employeeId: "EMP-015",
    employeeName: "Akin Adebayo",
    employeeInitials: "AA",
    dept: "Engineering",
    field: "Residential Address",
    fieldKey: "address",
    oldValue: "5 Eko Atlantic, Lagos",
    newValue: "28 Lekki Phase 2, Lagos",
    reason: "Bought a new home",
    status: "pending",
    submittedDate: "2026-06-30",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
  {
    id: "REQ-012",
    employeeId: "EMP-023",
    employeeName: "Gbenga Oduola",
    employeeInitials: "GO",
    dept: "Sales",
    field: "Bank Account Number",
    fieldKey: "accountNo",
    oldValue: "5678901236",
    newValue: "5678901237",
    reason: "Old account closed",
    status: "pending",
    submittedDate: "2026-06-30",
    reviewedBy: null,
    reviewedDate: null,
    rejectReason: null,
  },
];

/* ─── Audit trail entries (seed) ─── */
export const SEED_AUDIT = [
  {
    id: "AUD-001",
    action: "Employee record created",
    actor: "Ngozi Adeleke",
    actorId: "ADM-001",
    entityId: "EMP-001",
    entityName: "Amara Johnson",
    timestamp: "2021-06-01 09:00",
    field: null,
    from: null,
    to: null,
  },
  {
    id: "AUD-002",
    action: "Status changed to Active",
    actor: "Ngozi Adeleke",
    actorId: "ADM-001",
    entityId: "EMP-001",
    entityName: "Amara Johnson",
    timestamp: "2021-06-01 09:02",
    field: "status",
    from: "—",
    to: "Active",
  },
  {
    id: "AUD-003",
    action: "Profile change request approved",
    actor: "Ngozi Adeleke",
    actorId: "ADM-001",
    entityId: "EMP-010",
    entityName: "Chidi Nwachukwu",
    timestamp: "2026-06-22 10:15",
    field: "email",
    from: "chidi.old@hriscloud.com",
    to: "chidi.nwachukwu@hriscloud.com",
  },
  {
    id: "AUD-004",
    action: "Profile change request approved",
    actor: "Ngozi Adeleke",
    actorId: "ADM-001",
    entityId: "EMP-020",
    entityName: "Yemi Olatunji",
    timestamp: "2026-06-17 14:30",
    field: "phone",
    from: "+234 838 000 0000",
    to: "+234 838 901 2345",
  },
  {
    id: "AUD-005",
    action: "Profile change request approved",
    actor: "Ngozi Adeleke",
    actorId: "ADM-001",
    entityId: "EMP-017",
    entityName: "Seun Afolabi",
    timestamp: "2026-06-09 11:00",
    field: "phone",
    from: "+234 832 000 0000",
    to: "+234 832 345 6789",
  },
];

/* ─── Framer variants (reused across pages) ─── */
export const fadeUp = {
  hidden: { opacity: 0, y: 16 },
  visible: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.055, duration: 0.42, ease: [0.22, 1, 0.36, 1] },
  }),
};
